name: Deploy WordPress To EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext-base

      - name: Substitute secrets in wp-config.php
        run: |
          # Set up environment variables here, e.g., from your secrets
          export WORDPRESS_DB_NAME='${{ secrets.WORDPRESS_DB_NAME }}'
          export WORDPRESS_DB_USER='${{ secrets.WORDPRESS_DB_USER }}'
          export WORDPRESS_DB_PASSWORD=${{ secrets.WORDPRESS_DB_PASSWORD }}
          export WORDPRESS_DB_HOST=${{ secrets.WORDPRESS_DB_HOST }}
          for i in "./wordpress/wp-config.php";
            do 
          envsubst < $i > $i.tmp && mv $i.tmp $i;
          done

          sed -i "s/ = 'wp_';/\$table_prefix = 'wp_';/" ./wordpress/wp-config.php

      - name: Copy files to remote server using rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Set up SSH key
          echo "$SSH_PRIVATE_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          eval $(ssh-agent)
          ssh-add ssh_key.pem

          export REMOTE_USER=${{ secrets.REMOTE_USER }}
          export REMOTE_HOST=${{ secrets.REMOTE_HOST }}
          export REMOTE_PORT=${{ secrets.REMOTE_PORT }} 
          SOURCE_DIR="./wordpress/"  # Relative path to the source directory in your repository
          TARGET_DIR="/var/www/brainstorm.ayodele.cloud"   # Absolute path to the target directory on the remote server

          # Use rsync to copy files
          rsync -avz --delete $SOURCE_DIR $REMOTE_USER@$REMOTE_HOST:$TARGET_DIR

